AllCops:
  Include:
    - "**/Rakefile"
    - config.ru
  Exclude:
    - "**/*.gemspec"
    - "db/**/*"
    - "**/migrate/*.rb"
    - "bin/**/*"
    - "spec/**/*"

MethodLength:
  Max: 20

LineLength:
  Max: 160

Style/AccessModifierIndentation:
  EnforcedStyle: outdent

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/AlignHash:
  EnforcedHashRocketStyle: separator
  EnforcedColonStyle: separator
  EnforcedLastArgumentHashStyle: always_inspect

Style/AlignParameters:
  EnforcedStyle: with_first_parameter

Style/BracesAroundHashParameters:
  EnforcedStyle: no_braces

# Multi-line method chaining should be done with leading dots.
Style/DotPosition:
  EnforcedStyle: trailing

Style/Encoding:
  EnforcedStyle: when_needed

Style/FileName:
  Exclude:
    - "**/Rakefile"
    - "**/Gemfile"

Style/HashSyntax:
  EnforcedStyle: ruby19

Style/IfUnlessModifier:
  MaxLineLength: 80

Style/WhileUntilModifier:
  MaxLineLength: 80

Style/IndentHash:
  EnforcedStyle: consistent

Style/Next:
  EnforcedStyle: always

Style/NonNilCheck:
  IncludeSemanticChanges: true

Style/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: no_space

Style/TrivialAccessors:
  ExactNameMatch: true
  AllowPredicates: false
  AllowDSLWriters: true

EmptyLinesAroundBody: # prefer empty line for legibility
  Enabled: true

Documentation: # format too restricted
  Enabled: false

# bug in current rubocop release 0.21.0
Delegate:
  Enabled: true

Style/AccessModifierIndentation:
  EnforcedStyle: indent

Lint/AssignmentInCondition:
  AllowSafeAssignment: false

Lint/DefEndAlignment:
  AlignWith: def

Style/GlobalVars:
  AllowedVariables: [$]
