default: &database
  database:
    host: localhost
    username: postgres
    password: postgres

default: &api
  facebook_api:
    id: <%= ENV["FACEBOOK_API_ID"] %>
    secret: <%= ENV["FACEBOOK_API_SECRET"] %>
  marvel_api:
    address: "http://gateway.marvel.com/v1/public/"
    public_key: <%= ENV["MARVEL_API_PUBLIC"] %>
    private_key: <%= ENV["MARVEL_API_PRIVATE"] %>

development:
  secret_key_base: 663c684dc1fc83eadb8b8c33814b7e6ed8604637e03bbd029c8f2d0965d6e48348c208cc50af8a2230aa0cdb259496aa6b6806286eca9088149d0bcb2c4815d3
  <<: *database
  <<: *api

test:
  secret_key_base: d5367baa4c6a57815947daa85b33a1f4027e02d6f07fb81766ddaaee2b8715dbe9fe2193b7bb4aacfd277ed5878e22880a5bd43a836fe9fecdf4ae91f1680718
  <<: *database
  <<: *api

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  database:
    host: <%= ENV["DATABASE_HOST"] %>
    username: <%= ENV["DATABASE_USERNAME"] %>
    password: <%= ENV["DATABASE_PASSWORD"] %>
    <<: *api
